### ISSUE TITLE
Font rendering messing up

### ISSUE THREAD

**Issue by josh-king** [MrSpring/InGameFileExplorer#1]
When opening up an image, the font changes texture to bits of the picture that's being viewed.

![ss 2015-03-06 at 09 30 16](https://cloud.githubusercontent.com/assets/8937909/6536767/43c0a928-c448-11e4-9d02-8cdc859aa964.png)

Possible fix; Rebind the text after the image has been loaded

**Comment by MrSpring** [comment]
That's very strange, it dosn't happen when I open an image.

**Comment by MrSpring** [comment]
Version 0.1.2 might have fixed this issue.
